--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/TPAll
build-by-default: true
branches:
- PM5
- PM4
projects:
  TPAll:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
    lint:
      phpstan: false
...
