--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/TPAll
build-by-default: true
branches:
- PM4
projects:
  TPAll:
    path: TPAll/
    icon: icon-tpall.png
    lint:
      phpstan: false
...
