---
name: TPAll
main: matymare\tpall\Main
version: 1.4
api: 5.3.0
authors: [fernanACM, matymare]
description: Teleport all player to you!

commands:
  tpall:
    description: Teleport all players to you!
    usage: "/tpall"
    permission: tpall.command

permissions:
  tpall.command:
    default: op
...
