name: TPAll
main: matymare\tpall\Main
version: 1.2
api: 3.0.0
author: matymare
description: /tpall command!

commands:
  tpall:
    description: Teleport all players to you!
    usage: "/tpall"
    permission: tpall.command
